name = "SASLMR"
uuid = "c5384bee-8a12-426e-bc63-175ec2f1897e"
keywords = ["ANOVA", "julia"]
desc = "ANOVA for julia (sasLM wrapper)."
authors = ["Vladimir Arnautov <mail@pharmcat.net>"]
version = "0.1.0"

[deps]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"


[compat]
RCall = "0.13, 0.14"
StatsBase = "0.30, 0.31, 0.32, 0.33, 0.34"
StatsModels = "0.7"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]
